apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          email: nick@nickbunn.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token