apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  keys:
    - api-token
  path: secrets/cert-manager/cloudflare-api-token
  type: Opaque