Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@nrbunn 
billimek
/
k8s-gitops
8
274
45
Code
Issues
9
Pull requests
Discussions
Actions
Projects
Wiki
Security
Insights
k8s-gitops/kube-system/vault-secrets-operator/vault-secrets-operator.yaml
@billimek
billimek upgrade vaul secrets operator to 1.15.0
…
Latest commit 0c4cdf4 on Jun 28
 History
 2 contributors
@billimek@renovate-bot
35 lines (35 sloc)  851 Bytes
  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ricoberger.github.io/helm-charts
      chart: vault-secrets-operator
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: ricoberger-charts
        namespace: flux-system
      interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    #    image:
    #      repository: ricoberger/vault-secrets-operator
    #      tag: 1.2.3
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete