---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 6.6.4
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: photoprism/photoprism
      tag: "20220121"
    env:
      # -- Set the container timezone
      TZ: CST
      PHOTOPRISM_CONFIG_PATH: /config
      # -- Photoprism storage path
      PHOTOPRISM_STORAGE_PATH: /media/Photos/storage
      # -- Photoprism originals path
      PHOTOPRISM_ORIGINALS_PATH: /media/Photos/originals
      # -- Photoprism Import Path
      PHOTOPRISM_IMPORT_PATH: /media/Photos/import
      # -- Initial admin password. **BE SURE TO CHANGE THIS!**
      PHOTOPRISM_ADMIN_PASSWORD: "please-change"
      # -- Disable authentication / password protection
      PHOTOPRISM_PUBLIC: "false"
      # # -- Sets UID Photoprism runs under.
      # UID:  # 1000
      # # -- Sets GID Photoprism runs under.
      # GID:  # 1000
      # # -- Sets UMASK.
      # UMASK:  # 0000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: photoprism.nickbunn.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "photoprism.nickbunn.com"
    # podAnnotations:
    #   backup.velero.io/backup-volumes: config
    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        size: 2Gi
      media:
        enabled: true
        existingClaim: nfs-default-media-pvc  
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
