---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1769
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "prowlarr.nickbunn.com"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.nickbunn.com"
    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        size: 5Gi
      media:
        enabled: true
        existingClaim: nfs-media-pvc
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
    tolerations:
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
